# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Firebase"
  lane :beta do
    gradle(task: "clean assembleRelease")

    firebase_app_distribution(
      app: "1:17515048996:android:f8cc4c7994782f9da4a8b1",
      groups: "qa-tester",
      release_notes: "Testing fastlane beta"
    )
    
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Submit a new Beta version to the Google Play"
  lane :deploy do
    store_password = prompt(text: "Signing Store Password: ", secure_text: true)
    key_password = prompt(text: "Alias Key Password: ", secure_text: true)
    releaseFilePath = File.join(Dir.pwd, "..", "my-upload-key.keystore")
    gradle(task: 'clean')
    gradle(
      task: 'assemble',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => store_password,
        "android.injected.signing.key.alias" => "alias_name"
      }
    )
    upload_to_play_store(
      track: 'internal'
    )

  end
end
